### PR TITLE
Market with value

### PR DESCRIPTION
**Pull request by friedger**
This PR builds on top of #51 

It adds the possibility to 
* place and remove a bid (for information purpose only)
* attach a time limit for ownership transfer (afterwards the monster can be claimed back)
* attach a value to ownership transfer (transfer is executed once the value has been transferred)

There is no UI for that yet.

### CODE REVIEW

**Comment by friedger** [comment]
Currently, init_market.sh fails with 
    1554880ms thread-0   main.cpp:2584                 main                 ] Failed with error: Assert Exception (10)
    false: abort() called

when calling
cleos push action eosio.token transfer '["friedger", "monstereosio", "1.0000 EOS", "MTT0"]' -p friedger

**Comment by leordev** [comment]
Just referencing our project issue #35

**Comment by leordev** [comment]
@friedger is it already test and ready for merge? Do we need only the screens?

**Comment by friedger** [comment]
Yes, it is tested. Maybe you should review the code for security issues? Is it possible that another person gets the ownership? Is it possible that the new owner gets the monster for a different amount than agreed.

**Comment by friedger** [comment]
Closing it for now and sending a new PR to market_mobile.

**Pull request closed without merging**
